"""The blind-panel identifier scan: what BLOCKS a flight, and what does not.

`dev/blind_panel/stage.py` is the gate between a staged artifact and a judge.
It had no test, and on 2026-08-05 it blocked all five FRONTIER face-offs on
`reap` inside the word "reapplied" — in a docstring, in the v2.0 anchor, which
is constant across every flight and therefore discriminates nothing.

The naive fix is word boundaries, and it is WRONG: model identifiers are short
family STEMS matched as substrings on purpose, so `\\bqwen\\b` stops matching
`qwen3.6-27b` and silently disarms the scan for most of the roster. What
actually separates a leak from prose is the next character — a model name
continues with a separator or a digit, an accident continues with letters.

These tests exist because a scan that cries wolf gets overridden by habit, and
a scan that is quietly loosened stops protecting anything. Both failure modes
end the same way: a confident, well-argued, unblinded verdict.
"""

from __future__ import annotations

import importlib.util
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
_spec = importlib.util.spec_from_file_location(
    "blind_stage", ROOT / "dev" / "blind_panel" / "stage.py"
)
stage = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(stage)

PAT = re.compile("|".join(re.escape(s) for s in stage.IDENTIFIERS), re.I)


def blocks(text: str) -> bool:
    m = PAT.search(text)
    return stage._is_blocking(text, m) if m else False


class TestRealModelNamesStillBlock:
    """The regression that matters. Every one of these is a live roster name
    in the form it actually appears in generated code and READMEs."""

    @pytest.mark.parametrize(
        "text",
        [
            "qwen3.6-27b",
            "Qwen3-Next-Coder-80B",
            "gpt-oss-120b-a5-swarm-524k",
            "hy3-reap-200b-a21",
            "glm-4.7-flash",
            "step37-flash-196b-a11",
            "gemma-4-31b",
            "mistral-medium-3.5-128b",
            "deepseek-v4-flash",
            "laguna",
            "olmo-3.1-32b-instruct",
            "devstral-2-small-24b",
            "generated by qwen",
            "# model: GPT-OSS",
            "openai/qwen3",
        ],
    )
    def test_it_blocks(self, text):
        assert blocks(text), f"{text!r} must block a flight"

    def test_a_bare_stem_still_blocks(self):
        """Conservative on purpose: `reap` standing alone could be the quant
        name. Only a stem swallowed by a longer word is demoted."""
        assert blocks("the reap harvest")


class TestStemsInsideOrdinaryWordsAreDemoted:
    """Demoted, never dropped — still printed, still gets a human look."""

    @pytest.mark.parametrize(
        "text",
        [
            "before save data is reapplied on top",  # the exact 2026-08-05 blocker
            "reapply the modifier",
            "monsters reappear after a reload",
        ],
    )
    def test_it_does_not_block(self, text):
        assert not blocks(text)

    def test_the_frontier_anchor_is_judgeable(self):
        """The artifact that actually blocked the batch. If this ever blocks
        again, five staged flights are dead until someone re-reads the scan."""
        anchor = ROOT / "dev/blind_panel/anchors/v2.0/frontier-sonnet-20260803"
        if not anchor.is_dir():
            pytest.skip("v2.0 frontier anchor not present")
        assert not [h for h in stage.scan(anchor) if h[3]]


class TestFrameworkNamesAreAdvisory:
    """Present in EVERY arm's generated pyproject/README/title screen, so they
    discriminate nothing — and the judge already knows it is reading an
    agent's output."""

    @pytest.mark.parametrize(
        "text", ["a text adventure by Ouroboros", "built with Claude", "llmvp shim"]
    )
    def test_it_does_not_block(self, text):
        assert not blocks(text)


class TestAnAdvisoryCannotMaskALeak:
    """The old scan took the FIRST hit per file and stopped. Once some hits
    are demoted that becomes a hole: a false positive on line 1 would hide a
    real model name on line 2 — the scan would report 'no model names —
    judgeable' on a leaked packet."""

    def test_a_leak_after_an_advisory_is_still_found(self, tmp_path):
        (tmp_path / "world.py").write_text(
            "# save data is reapplied on top\n" "# generated by qwen3.6-27b\n"
        )
        hits = stage.scan(tmp_path)
        assert any(h[3] for h in hits), "the real leak on line 2 must survive"
        assert any(not h[3] for h in hits), "the advisory should still be reported"

    def test_both_are_reported_from_one_file(self, tmp_path):
        (tmp_path / "a.py").write_text("reapplied\nqwen3\n")
        hits = stage.scan(tmp_path)
        assert len(hits) == 2

    def test_a_clean_file_reports_nothing(self, tmp_path):
        (tmp_path / "a.py").write_text("class Room:\n    pass\n")
        assert stage.scan(tmp_path) == []
