"""
Card Lookup Tool — lets Kippa answer questions about specific Kipukas cards.

Loads the card catalog JSON (generated by build-card-catalog.ts) and provides
fuzzy search by title, slug, tags, or card type.
"""

import json
import os
from pathlib import Path
from typing import Dict, List, Any

from tools.registry import get_registry, Tool

# ---------------------------------------------------------------------------
# Load catalog once at import time
# ---------------------------------------------------------------------------

_CATALOG: List[Dict[str, Any]] = []
_CATALOG_PATH = (
    Path(__file__).resolve().parent.parent / "knowledge" / "cards_catalog.json"
)


def _load_catalog() -> List[Dict[str, Any]]:
    """Load the card catalog JSON from the knowledge directory."""
    global _CATALOG
    if _CATALOG:
        return _CATALOG
    if not _CATALOG_PATH.exists():
        return []
    with open(_CATALOG_PATH, "r", encoding="utf-8") as f:
        _CATALOG = json.load(f)
    return _CATALOG


def _normalize(s: str) -> str:
    """Lowercase, strip, collapse whitespace, remove common punctuation."""
    return (
        s.lower()
        .replace("_", " ")
        .replace("-", " ")
        .replace(":", "")
        .replace("'", "")
        .replace('"', "")
        .strip()
    )


def _fuzzy_match(query: str, cards: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Return cards matching the query.  Tries exact slug, then substring on
    title, then tags, then description.  Returns all matches scored by
    relevance.
    """
    q = _normalize(query)
    if not q:
        return []

    scored: List[tuple] = []

    for card in cards:
        slug_norm = _normalize(card.get("slug", ""))
        title_norm = _normalize(card.get("title", ""))
        tags_norm = _normalize(card.get("tags", ""))
        desc_norm = _normalize(card.get("description", "") or "")
        type_norm = _normalize(card.get("type", ""))

        # Exact slug match — highest score
        if q == slug_norm:
            scored.append((100, card))
            continue

        # Title contains query
        if q in title_norm:
            # Bonus for starts-with
            score = 90 if title_norm.startswith(q) else 80
            scored.append((score, card))
            continue

        # Query words all appear in title
        q_words = q.split()
        if q_words and all(w in title_norm for w in q_words):
            scored.append((70, card))
            continue

        # Tags match
        if q in tags_norm:
            scored.append((50, card))
            continue

        # Type/variation match
        if q == type_norm:
            scored.append((40, card))
            continue

        # Description contains query
        if q in desc_norm:
            scored.append((30, card))
            continue

    # Sort by score descending
    scored.sort(key=lambda x: x[0], reverse=True)
    return [card for _, card in scored]


def _format_card(card: Dict[str, Any]) -> Dict[str, Any]:
    """Format a card for tool output — compact, relevant fields only."""
    result: Dict[str, Any] = {
        "title": card.get("title"),
        "type": card.get("type"),
        "url": card.get("url"),
    }

    # Include non-null optional fields
    for field in [
        "variation",
        "genetic_disposition",
        "motivation",
        "habitat",
        "scarcity",
        "die",
        "brawl_sequence",
        "play_style",
        "tamability",
    ]:
        val = card.get(field)
        if val is not None:
            result[field] = val

    # Stats (only if non-zero)
    if card.get("injury_tolerance", 0) > 0:
        result["injury_tolerance"] = card["injury_tolerance"]
    if card.get("movement", 0) > 0:
        result["movement"] = card["movement"]

    # Keal means
    keal = card.get("keal_means", [])
    if keal:
        result["keal_means"] = keal

    # Description
    desc = card.get("description")
    if desc:
        result["description"] = desc

    # Tags
    tags = card.get("tags")
    if tags:
        result["tags"] = tags

    return result


# ---------------------------------------------------------------------------
# Tool execution
# ---------------------------------------------------------------------------


def _exec_card_lookup(params: dict) -> str:
    """Execute the card_lookup tool."""
    query = params.get("query", "").strip()
    if not query:
        return json.dumps({"error": "query parameter is required"})

    catalog = _load_catalog()
    if not catalog:
        return json.dumps({"error": "Card catalog not loaded"})

    matches = _fuzzy_match(query, catalog)

    if not matches:
        # Try individual words as fallback
        words = query.split()
        if len(words) > 1:
            for word in words:
                if len(word) >= 3:
                    matches.extend(_fuzzy_match(word, catalog))
            # Deduplicate by slug
            seen = set()
            unique = []
            for card in matches:
                if card["slug"] not in seen:
                    seen.add(card["slug"])
                    unique.append(card)
            matches = unique

    if not matches:
        return json.dumps(
            {"results": [], "message": f"No cards found matching '{query}'"}
        )

    # Limit to top 5 results
    top = matches[:5]
    formatted = [_format_card(c) for c in top]

    return json.dumps(
        {"results": formatted, "total_matches": len(matches)}, ensure_ascii=False
    )


# ---------------------------------------------------------------------------
# Registration
# ---------------------------------------------------------------------------

_registry = get_registry()
_registry.register(
    Tool(
        name="card_lookup",
        description=(
            "Look up a Kipukas card by name, slug, type, or keywords. "
            "Returns card details including type, stats, keal means, "
            "genetic disposition, description, and lore."
        ),
        parameters={
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": (
                        "Search query — card name, slug, tags, or card type "
                        "(e.g. 'hilbert', 'frost otter', 'Species', 'dragon')"
                    ),
                }
            },
            "required": ["query"],
        },
        execute=_exec_card_lookup,
    )
)
